default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: catalog-service_development

test:
  <<: *default
  database: catalog-service_test

production:
  <<: *default
  database: catalog-service_production
  username: catalog-service
  password: <%= ENV['CATALOG-SERVICE_DATABASE_PASSWORD'] %>
